name: autopew

channels:
  - conda-forge # get things from conda-forge first
  - defaults

dependencies:
  - python=3.10
  # pandas and scientific python
  - numpy
  - pandas>=1.0
  - xlrd
  - openpyxl
  - psutil
  - matplotlib
  - pillow
  - scipy
  # Tools
  - jupyter
  - jupyterlab
  - jupyterlab-spellchecker
  - jupyterlab_code_formatter
  - ipykernel
  - pip
  - black
  - isort
  - pytest
  - pytest-runner
  - pytest-cov
  - coverage
  - codecov
  - sphinx_rtd_theme
  - recommonmark
  - versioneer
  - twine
  - pip:
      - sphinx-autodoc-annotation
      - -e . # install the local autopew package

# conda env create -f environment.yml
# python -m ipykernel install --user --name autopew

# conda activate autopew

# install autopew from here

# conda deactivate autopew
# conda env remove -n autopew
# jupyter kernelspec uninstall autopew

# make sure to launch Jupyter, atom etc from the command line after activating
