name: DocsTest

on:
  push:
  pull_request:
    branches:
      - develop
      - feature/**
  schedule:
    - cron: "0 0 1 * *" # monthly


jobs:
  docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
        with:
          version: "latest"
          activate-environment: true
          python-version: "3.13"
          enable-cache: true
          cache-dependency-glob: |
                **/pyproject.toml
                **/uv.lock
            
      - name: Create Venv
        run: |
          uv sync --group docs

      - name: Build
        run: |
          cd docs && make html
